#### 1. Extract

In [3]:
import pyodbc 
import pandas as pd

In [2]:
source_conn = pyodbc.connect('Driver={SQL Server};'
    'Server=localhost;'
    'Database=BookStore_EG;'
    'Trusted_Connection=yes;')

In [8]:
df_customer = pd.read_sql ("select * from VCustomer", source_conn)
df_customer.head(5)

<ipython-input-8-1649a782a82e>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customer = pd.read_sql ("select * from VCustomer", source_conn)

   CustomerID      FullName   City
0           1        Shaker   None
1           2      El-Gamal   None
2           3        Asmaa   Tanta
3           4        Rania    Giza
4           5  Nour Ibrahim   None

In [9]:
df_book = pd.read_sql ("select * from VBook", source_conn)
df_book.head(5)

<ipython-input-9-66590a861a39>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_book = pd.read_sql ("select * from VBook", source_conn)

,BookID,Title,Price,CategoryDescription,AuthorName
0,1,Chemistry Today 1,72.66,Chemistry,Fekry Abaza
1,1,Chemistry Today 1,72.66,Chemistry,Ahmed Abdel Moati Hegazy
2,1,Chemistry Today 1,72.66,Chemistry,Ahmed El-Desouky
3,2,Islamic Studies 2,80.34,Religion,Baligh Hamdy
4,2,Islamic Studies 2,80.34,Religion,Ahmed El-Hefnawy

In [11]:
df_factorder = pd.read_sql ("select * from VOrder", source_conn)
df_factorder.head(10)

<ipython-input-11-7acf2e39cddf>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_factorder = pd.read_sql ("select * from VOrder", source_conn)

   OrderID  CustomerID   OrderDate  BookID  TotalAmount  Quantity
0        1         NaN  2020-12-17     198       180.70       1.0
1        1         NaN  2020-12-17     256       114.14       2.0
2        1         NaN  2020-12-17     393       188.30       1.0
3        1         NaN  2020-12-17     492       218.49       1.0
4        1         NaN  2020-12-17     996          NaN       1.0
5        2       379.0  2020-03-03      87       150.25       1.0
6        2       379.0  2020-03-03     538          NaN       2.0
7        2       379.0  2020-03-03     575          NaN       3.0
8        3       696.0  2020-07-05      94        85.78       2.0
9        3       696.0  2020-07-05     270          NaN       2.0

In [12]:
source_conn.close()

#### 2. Transform

In [ ]:
### matplotib

In [ ]:
## Nulls
## Dublicated Values
## Data Types 
## Outliers  (age ->  12 -> 80)   (250),  (salary : 1200:5000)   / 30000 CTO
## Rename Columns
## AddingColumns
## Data Cleaning (salary "50$" -> "50") , "Cairo" -> "Cairo, cairo" , "Alexandria" -> "Alexandria, Alex"

In [ ]:
## Nulls  
## Data Types
## Columns Names

In [14]:
df_customer.head(5)

   CustomerID      FullName   City
0           1        Shaker   None
1           2      El-Gamal   None
2           3        Asmaa   Tanta
3           4        Rania    Giza
4           5  Nour Ibrahim   None

In [16]:
df_customer.shape

(2000, 3)

In [17]:
df_customer.columns

Index(['CustomerID', 'FullName', 'City'], dtype='object')

In [18]:
df_customer.dtypes

CustomerID     int64
FullName      object
City          object
dtype: object

In [19]:
df_customer.isnull().sum()

CustomerID      0
FullName        0
City          872
dtype: int64

In [24]:
df_customer['City'].value_counts()

City
Alexandria             72
Suez                   64
El-Mahalla El-Kubra    63
Cairo                  63
Giza                   61
Shubra El-Kheima       58
Mansoura               57
Port Said              53
Tanta                  48
Asyut                  43
Beni Suef              39
Ismailia               38
Aswan                  38
Damietta               37
Kafr El-Sheikh         36
New Valley             36
Sohag                  35
Faiyum                 35
Luxor                  33
Minya                  33
Matrouh                32
Zagazig                31
South Sinai            29
Helwan                 26
Qena                   24
North Sinai            24
Red Sea                20
Name: count, dtype: int64

In [28]:
df_customer.fillna({
    "City" : "Unknown"
}, inplace=True)

In [29]:
df_customer.isnull().sum()

CustomerID    0
FullName      0
City          0
dtype: int64

In [ ]:
df_customer['City'].value_counts()

In [32]:
df_customer.drop_duplicates(inplace=True)

In [33]:
df_customer.shape

(2000, 3)

In [35]:
df_book.head(5)

,BookID,Title,Price,CategoryDescription,AuthorName
0,1,Chemistry Today 1,72.66,Chemistry,Fekry Abaza
1,1,Chemistry Today 1,72.66,Chemistry,Ahmed Abdel Moati Hegazy
2,1,Chemistry Today 1,72.66,Chemistry,Ahmed El-Desouky
3,2,Islamic Studies 2,80.34,Religion,Baligh Hamdy
4,2,Islamic Studies 2,80.34,Religion,Ahmed El-Hefnawy

In [36]:
df_book.shape

(3009, 5)

In [37]:
df_book.dtypes

BookID                   int64
Title                   object
Price                  float64
CategoryDescription     object
AuthorName              object
dtype: object

In [38]:
df_book.isnull().sum()

BookID                  0
Title                   0
Price                   0
CategoryDescription     0
AuthorName             50
dtype: int64

In [39]:
df_book.value_counts()

BookID  Title                   Price   CategoryDescription  AuthorName
1       Chemistry Today 1       72.66   Chemistry            Ahmed Abdel Moati Hegazy    1
671     Egyptian Art 671        204.75  Art                  Mostafa Amin                1
669     History of Egypt 669    230.08  History              Ahmed Sedky                 1
                                                             Alaa Al-Aswany              1
                                                             Mohamed Abdel Nabi          1
                                                                                        ..
334     Islamic Studies 334     175.68  Religion             Mohamed Ibrahim Mabrouk     1
335     History of Egypt 335    146.92  History              Ahmed Naji                  1
                                                             Galal Amin                  1
                                                             Mohamed El-Banna            1
1000    Physics Explained 1000  133.67  Physics              Mohamed Abdel Wahab         1
Name: count, Length: 2959, dtype: int64

In [42]:
df_book.fillna({
    "AuthorName" : df_book['AuthorName'].mode()[0]
}, inplace=True)

In [44]:
df_book.head()

,BookID,Title,Price,CategoryDescription,AuthorName
0,1,Chemistry Today 1,72.66,Chemistry,Fekry Abaza
1,1,Chemistry Today 1,72.66,Chemistry,Ahmed Abdel Moati Hegazy
2,1,Chemistry Today 1,72.66,Chemistry,Ahmed El-Desouky
3,2,Islamic Studies 2,80.34,Religion,Baligh Hamdy
4,2,Islamic Studies 2,80.34,Religion,Ahmed El-Hefnawy

In [45]:
df_factorder.head(5)

   OrderID  CustomerID   OrderDate  BookID  TotalAmount  Quantity
0        1         NaN  2020-12-17     198       180.70       1.0
1        1         NaN  2020-12-17     256       114.14       2.0
2        1         NaN  2020-12-17     393       188.30       1.0
3        1         NaN  2020-12-17     492       218.49       1.0
4        1         NaN  2020-12-17     996          NaN       1.0

In [46]:
df_factorder.shape

(32034, 6)

In [47]:
df_factorder.columns

Index(['OrderID', 'CustomerID', 'OrderDate', 'BookID', 'TotalAmount',
       'Quantity'],
      dtype='object')

In [48]:
df_factorder.dtypes

OrderID          int64
CustomerID     float64
OrderDate       object
BookID           int64
TotalAmount    float64
Quantity       float64
dtype: object

In [49]:
df_factorder.isnull().sum()

OrderID           0
CustomerID     1373
OrderDate         0
BookID            0
TotalAmount    1620
Quantity       1511
dtype: int64

In [53]:
CustomerID = 0
mean_total_amount = int(df_factorder['TotalAmount'].mean())
median_Quantity = int(df_factorder['Quantity'].median())

In [54]:
df_factorder.fillna({
    "CustomerID" : CustomerID,
    "TotalAmount" : mean_total_amount,
    "Quantity" : median_Quantity
}, inplace=True)

In [55]:
df_factorder.isnull().sum()

OrderID        0
CustomerID     0
OrderDate      0
BookID         0
TotalAmount    0
Quantity       0
dtype: int64

In [57]:
df_factorder.dtypes

OrderID          int64
CustomerID     float64
OrderDate       object
BookID           int64
TotalAmount    float64
Quantity       float64
dtype: object

In [60]:
df_factorder['OrderDate'] = df_factorder['OrderDate'].str.replace('-','')

In [61]:
df_factorder['CustomerID'] = df_factorder['CustomerID'].astype(int) 
df_factorder['Quantity'] = df_factorder['Quantity'].astype(int) 
df_factorder['OrderDate'] = df_factorder['OrderDate'].astype(int)

In [62]:
df_factorder.dtypes

OrderID          int64
CustomerID       int32
OrderDate        int32
BookID           int64
TotalAmount    float64
Quantity         int32
dtype: object

In [63]:
df_factorder.head(5)

   OrderID  CustomerID  OrderDate  BookID  TotalAmount  Quantity
0        1           0   20201217     198       180.70         1
1        1           0   20201217     256       114.14         2
2        1           0   20201217     393       188.30         1
3        1           0   20201217     492       218.49         1
4        1           0   20201217     996       149.00         1

#### 3. Load (BookDWH)

In [77]:
dwh_conn = pyodbc.connect('Driver={SQL Server};'
    'Server=localhost;'
    'Database=BookDWH;'
    'Trusted_Connection=yes;')

cursor = dwh_conn.cursor()

In [67]:
df_customer.dtypes

CustomerID     int64
FullName      object
City          object
dtype: object

In [70]:
for index, row in df_customer.iterrows():
    cursor.execute('INSERT INTO DimCustomer VALUES(?, ?, ?)', row['CustomerID'], row['FullName'], row['City'])
dwh_conn.commit()

In [72]:
df_book.head(5)

,BookID,Title,Price,CategoryDescription,AuthorName
0,1,Chemistry Today 1,72.66,Chemistry,Fekry Abaza
1,1,Chemistry Today 1,72.66,Chemistry,Ahmed Abdel Moati Hegazy
2,1,Chemistry Today 1,72.66,Chemistry,Ahmed El-Desouky
3,2,Islamic Studies 2,80.34,Religion,Baligh Hamdy
4,2,Islamic Studies 2,80.34,Religion,Ahmed El-Hefnawy

In [78]:
for index, row in df_book.iterrows():
    cursor.execute('INSERT INTO DimBook VALUES(?, ?, ?, ? ,? )', row['BookID'], row['Title'], row['Price'], row['CategoryDescription'], row['AuthorName'])
dwh_conn.commit()

In [79]:
df_factorder.head(5)

   OrderID  CustomerID  OrderDate  BookID  TotalAmount  Quantity
0        1           0   20201217     198       180.70         1
1        1           0   20201217     256       114.14         2
2        1           0   20201217     393       188.30         1
3        1           0   20201217     492       218.49         1
4        1           0   20201217     996       149.00         1

In [80]:
df_dimbook = pd.read_sql ("select * from DimBook", dwh_conn)
df_dimbook.head(5)

<ipython-input-80-a3233abec1af>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dimbook = pd.read_sql ("select * from DimBook", dwh_conn)

,BookSK,BookID,Title,Price,CategoryDesc,AuhterName
0,100,1,Chemistry Today 1,72.66,Chemistry,Fekry Abaza
1,101,1,Chemistry Today 1,72.66,Chemistry,Ahmed Abdel Moati Hegazy
2,102,1,Chemistry Today 1,72.66,Chemistry,Ahmed El-Desouky
3,103,2,Islamic Studies 2,80.34,Religion,Baligh Hamdy
4,104,2,Islamic Studies 2,80.34,Religion,Ahmed El-Hefnawy

In [81]:
df_factorder = pd.merge(df_factorder, df_dimbook, how='inner', on='BookID')

In [87]:
df_factorder = df_factorder[["OrderID", "CustomerID", "OrderDate", "BookSK", "TotalAmount", "Quantity"]]

In [88]:
df_factorder.head(5)

   OrderID  CustomerID  OrderDate  BookSK  TotalAmount  Quantity
0        1           0   20201217     702        180.7         1
1        1           0   20201217     703        180.7         1
2       79         640   20230720     702        180.7         2
3       79         640   20230720     703        180.7         2
4      608          87   20200822     702        180.7         2

In [90]:
for index, row in df_factorder.iterrows():
    cursor.execute('INSERT INTO FactOrders VALUES(?, ?, ?, ? ,?, ? )', row['OrderID'], row['CustomerID'], row['OrderDate'], row['BookSK'], row['TotalAmount'], row['Quantity'])
dwh_conn.commit()

In [91]:
dwh_conn.close()